--- 

- hosts: all
  become: true
  tasks: 
  
#  - name: update repo index
#    yum:
#        update_cache: yes
#    when: ansible_distribution == "Fedora"

  - name: install apache2, liabapch2-mod-php packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install httpd, and php packages
    dnf:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Fedora"



