- name: install apache2, liabapch2-mod-php packages
  tags: apache, apache2, ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start httpd ( Fedora )
  tags: apache,fedora,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change e-mail address for admin
  tags: apache,fedora,httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin somebody@somewhere.org
  when: ansible_distribution == "Fedora"
  notify: restart_apache

#- name: restart httpd ( Fedora )
#  tags: apache,fedora,httpd
#  service:
#    name: "{{ apache_service }}"
#    state: restarted
#  when: httpd.changed

- name: copy default html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
